#!/usr/bin/env pwsh
# ============================================================================
# CLEANUP AND PUSH SCRIPT
# Removes build artifacts from Git tracking and pushes clean develop branch
# ============================================================================

Write-Host "🧹 Starting Git cleanup and push process..." -ForegroundColor Cyan
Write-Host ""

# Step 1: Add comprehensive Flutter/Dart entries to .gitignore
Write-Host "📝 Step 1: Updating .gitignore with Flutter build patterns..." -ForegroundColor Yellow

$flutterIgnorePatterns = @"

# ============================================================================
# Flutter & Dart Build Artifacts (Added $(Get-Date -Format 'yyyy-MM-dd'))
# ============================================================================

# Flutter build outputs
/build/
*.apk
*.aab
*.ipa
*.so
*.dylib
*.dll

# Dart tool
/.dart_tool/
/.packages
.flutter-plugins
.flutter-plugins-dependencies

# iOS Flutter artifacts
/ios/Flutter/Flutter.framework
/ios/Flutter/Flutter.podspec
/ios/Flutter/App.framework
/ios/Flutter/Generated.xcconfig
/ios/.symlinks/
/ios/Pods/
**/Flutter/*.framework

# Android Flutter artifacts
/android/.gradle/
/android/captures/
/android/local.properties
/android/app/release/
/android/app/profile/
/android/app/debug/

# Large compiled artifacts
*.dill
libflutter.so*
libapp.so*

# Build reports
/build/reports/
"@

Add-Content -Path .gitignore -Value $flutterIgnorePatterns
Write-Host "   ✅ .gitignore updated" -ForegroundColor Green
Write-Host ""

# Step 2: Remove build artifacts from Git tracking
Write-Host "🗑️  Step 2: Removing build artifacts from Git tracking..." -ForegroundColor Yellow

$pathsToRemove = @(
    "build",
    ".dart_tool",
    "ios/Flutter/Flutter.framework",
    "android/.gradle",
    "android/app/release",
    "android/app/profile"
)

foreach ($path in $pathsToRemove) {
    if (Test-Path $path) {
        Write-Host "   Removing: $path" -ForegroundColor Gray
        git rm -r --cached $path 2>&1 | Out-Null
    }
}

# Remove any .apk, .aab, .so files
Write-Host "   Removing: *.apk, *.aab, *.so files" -ForegroundColor Gray
git rm --cached "*.apk" 2>&1 | Out-Null
git rm --cached "*.aab" 2>&1 | Out-Null
git rm --cached "*.so" 2>&1 | Out-Null
git rm --cached "*.dill" 2>&1 | Out-Null

Write-Host "   ✅ Build artifacts removed from tracking" -ForegroundColor Green
Write-Host ""

# Step 3: Stage and commit the cleanup
Write-Host "💾 Step 3: Creating commit with cleaned repository..." -ForegroundColor Yellow

git add .gitignore
git add -A

$commitMessage = "chore: Remove build artifacts and update .gitignore for Flutter

- Remove .dart_tool/ from tracking (~112MB app.dill files)
- Remove build/ directory (APK/AAB files ~244MB)
- Remove .so libraries (>125MB each)
- Add comprehensive Flutter build patterns to .gitignore

This ensures only source code is tracked, not compiled outputs.
Build artifacts will be generated by CI/CD workflows."

git commit -m $commitMessage

if ($LASTEXITCODE -ne 0) {
    Write-Host "   ❌ Commit failed" -ForegroundColor Red
    exit 1
}

Write-Host "   ✅ Changes committed" -ForegroundColor Green
Write-Host ""

# Step 4: Verify no large files remain
Write-Host "🔍 Step 4: Verifying no large files in commit..." -ForegroundColor Yellow

$largeFiles = git ls-files | Where-Object {
    $file = $_
    if (Test-Path $file) {
        $size = (Get-Item $file).Length / 1MB
        $size -gt 50
    }
}

if ($largeFiles) {
    Write-Host "   ⚠️  Warning: Large files still tracked:" -ForegroundColor Yellow
    $largeFiles | ForEach-Object {
        $size = [math]::Round((Get-Item $_).Length / 1MB, 2)
        Write-Host "      - $_ ($size MB)" -ForegroundColor Yellow
    }
    Write-Host ""
    $continue = Read-Host "Continue with push anyway? (y/N)"
    if ($continue -ne "y") {
        Write-Host "   ❌ Push cancelled" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "   ✅ No large files detected" -ForegroundColor Green
}
Write-Host ""

# Step 5: Push to GitHub
Write-Host "🚀 Step 5: Pushing clean develop branch to GitHub..." -ForegroundColor Yellow
Write-Host "   This may take a few minutes for initial push..." -ForegroundColor Gray
Write-Host ""

git push -u origin develop

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "✅ SUCCESS! Clean develop branch pushed to GitHub" -ForegroundColor Green
    Write-Host ""
    Write-Host "📊 Repository Status:" -ForegroundColor Cyan
    Write-Host "   • Build artifacts removed from tracking" -ForegroundColor White
    Write-Host "   • .gitignore properly configured" -ForegroundColor White
    Write-Host "   • develop branch synced with origin/develop" -ForegroundColor White
    Write-Host ""
    Write-Host "🎯 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Run: .\release_beta.ps1" -ForegroundColor White
    Write-Host "   2. CI/CD will trigger and build artifacts" -ForegroundColor White
    Write-Host "   3. Monitor at: https://github.com/larrybesant/MIXMINGLE/actions" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host ""
    Write-Host "❌ Push failed" -ForegroundColor Red
    Write-Host ""
    Write-Host "Common issues:" -ForegroundColor Yellow
    Write-Host "   1. Authentication - Set PAT: git remote set-url origin https://TOKEN@github.com/larrybesant/MIXMINGLE.git" -ForegroundColor White
    Write-Host "   2. Network/firewall blocking large uploads" -ForegroundColor White
    Write-Host "   3. Still have large files tracked (check output above)" -ForegroundColor White
    Write-Host ""
    exit 1
}
