// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:web:17c9f4f34a8fb666077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-RE3FC9DMJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbS7zVY2o4S1-OOPkqFuUXz5B5hmmsS0U',
    appId: '1:980846719834:android:046ccc25cd68756f077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15xj5jE4UtiLoidJ4QmpJr47ZxdY6AQk',
    appId: '1:980846719834:ios:613eed02e264fd7e077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    iosBundleId: 'com.mixandmingle.mixAndMingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD15xj5jE4UtiLoidJ4QmpJr47ZxdY6AQk',
    appId: '1:980846719834:ios:613eed02e264fd7e077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    iosBundleId: 'com.mixandmingle.mixAndMingle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBmz9ybuDRCA2dAVjFZVj7R7wrDL0wTYU',
    appId: '1:980846719834:web:bafb8713c5680a95077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-DWQMCTJKWE',
  );
}
