// This file is generated by FlutterFire CLI
// Project: mix-and-mingle-v2

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:web:a8981485ee574b25077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
    measurementId: 'G-XWZLSPYZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:android:8752ec20ee1dfb78077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  // ⚠️ WARNING: This iOS config is using the WEB appId — iOS was NOT registered
  // in Firebase. You MUST:
  //  1. Go to Firebase Console → Project Settings → Add App → iOS
  //  2. Enter bundle ID: com.mixandmingle.mixAndMingle
  //  3. Download GoogleService-Info.plist → place in ios/Runner/
  //  4. Run: flutterfire configure   (regenerates this file with the real iOS appId)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId:
        '1:980846719834:web:a8981485ee574b25077963', // ← WRONG: replace with iOS appId
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:web:a8981485ee574b25077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:web:a8981485ee574b25077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB8KXjs0EqnJQdbaKVkX9nwsj07RK2ffM4',
    appId: '1:980846719834:web:a8981485ee574b25077963',
    messagingSenderId: '980846719834',
    projectId: 'mix-and-mingle-v2',
    authDomain: 'mix-and-mingle-v2.firebaseapp.com',
    storageBucket: 'mix-and-mingle-v2.firebasestorage.app',
  );
}
