// Mocks generated by Mockito 5.4.6 from annotations
// in mix_and_mingle/test/chat/chat_list_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

// import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:mix_and_mingle/services/profile_service.dart' as _i2;
import 'package:mix_and_mingle/shared/models/user_profile.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i2.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserProfile?> getCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue: _i3.Future<_i4.UserProfile?>.value(),
      ) as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<_i4.UserProfile?> getUserProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i3.Future<_i4.UserProfile?>.value(),
      ) as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<void> updateUserProfile(_i4.UserProfile? profile) => (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> createInitialProfile(
    String? userId,
    String? email,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInitialProfile,
          [
            userId,
            email,
            displayName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateOnlineStatus(
    String? userId,
    bool? isOnline,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOnlineStatus,
          [
            userId,
            isOnline,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.UserProfile>> searchUsersByInterests(List<String>? interests) => (super.noSuchMethod(
        Invocation.method(
          #searchUsersByInterests,
          [interests],
        ),
        returnValue: _i3.Future<List<_i4.UserProfile>>.value(<_i4.UserProfile>[]),
      ) as _i3.Future<List<_i4.UserProfile>>);

  @override
  _i3.Future<List<_i4.UserProfile>> getNearbyUsers(
    double? latitude,
    double? longitude,
    double? radiusKm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyUsers,
          [
            latitude,
            longitude,
            radiusKm,
          ],
        ),
        returnValue: _i3.Future<List<_i4.UserProfile>>.value(<_i4.UserProfile>[]),
      ) as _i3.Future<List<_i4.UserProfile>>);

  @override
  _i3.Stream<_i4.UserProfile?> streamCurrentUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #streamCurrentUserProfile,
          [],
        ),
        returnValue: _i3.Stream<_i4.UserProfile?>.empty(),
      ) as _i3.Stream<_i4.UserProfile?>);

  @override
  _i3.Stream<_i4.UserProfile?> streamUserProfile(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #streamUserProfile,
          [userId],
        ),
        returnValue: _i3.Stream<_i4.UserProfile?>.empty(),
      ) as _i3.Stream<_i4.UserProfile?>);

  @override
  _i3.Future<List<_i4.UserProfile>> searchUsers(String query) => (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.UserProfile>>.value(<_i4.UserProfile>[]),
      ) as _i3.Future<List<_i4.UserProfile>>);
}
